# wekan -- [Wekan](https://wekan.github.io/)
# @default -- [example](./examples/wekan.yaml)
wekan:
  # wekan.enabled -- Enable Wekan
  enabled: false
  name: wekan
  destination:
    # wekan.destination.namespace -- Namespace
    namespace: "pm-apps"
  # wekan.repoURL -- Repo URL
  # @default -- [repo](https://github.com/wekan/charts)
  repoURL: "https://wekan.github.io/charts"
  # wekan.chart -- Chart
  chart: "wekan"
  # wekan.targetRevision -- [wekan Helm chart](https://github.com/wekan/charts/tree/master/charts/wekan)
  targetRevision: "1.1.*"
  # wekan.values -- Helm values
  # @default -- [upstream values](https://github.com/wekan/charts/blob/master/charts/wekan/values.yaml)
  values: {}

# taiga -- [Taiga](https://taiga.io/)
# @default -- [example](./examples/taiga.yaml)
taiga:
  # taiga.enabled -- Enable Taiga
  enabled: false
  name: taiga
  destaination:
    # taiga.destination.namespace -- Namespace
    namespace: "pm-apps"
  # taiga.repoURL -- Repo URL
  # @default -- [repo](https://github.com/nemonik/taiga-helm)
  repoURL: "https://nemonik.github.io/helm-charts"
  # taiga.chart -- Chart
  chart: "taiga"
  # taiga.targetRevision -- [taiga Helm chart](https://github.com/nemonik/taiga-helm)
  targetRevision: "6.4.*"
  # taiga.values -- Helm values
  # @default -- [upstream values](https://github.com/nemonik/taiga-helm/blob/master/values.yaml)
  values: {}
