# Test exportarr
persistence:
  config:
    enabled: true
    type: emptyDir

additionalContainers:
  exportarr:
    name: exportarr
    image: ghcr.io/onedr0p/exportarr:master@sha256:2f6c2c583d11cd82252f31dec2965645a461af6af0231e87dbd736c7b16cca1c
    imagePullPolicy: IfNotPresent
    args: ["prowlarr"]
    env:
    - name: PORT
      value: "32123"
    - name: URL
      value: "http://localhost"
    - name: CONFIG
      value: "/config/config.xml"
    ports:
    - name: exportarr
      containerPort: 32123
    volumeMounts:
    - name: config
      mountPath: /config
      readOnly: true
