apiVersion: v2
name: media-apps
description: Argo CD app-of-apps config for media applications
type: application
# version and appVersion are in sync in this chart!
version: 0.2.0
appVersion: 0.2.0
home: https://git.reeb.io/pree/helm-charts/src/branch/master/charts/media-apps
sources:
  - https://git.reeb.io/pree/helm-charts
maintainers:
  - name: Pascal Reeb (pree)
    email: pascal@reeb.io
dependencies:
  - name: argoconfig
    version: 0.7.2
    repository: https://charts.adfinis.com
