{{- if .Values.metrics.enabled }}
{{- include "bjw-s.common.loader.init" . -}}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "bjw-s.common.lib.chart.names.fullname" . }}
  labels:
    {{- include "bjw-s.common.lib.controller.metadata.labels" . | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "bjw-s.common.lib.metadata.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      {{- with .Values.metrics.serviceMonitor.interval }}
      interval: {{ . }}
      {{- end }}
      {{- with .Values.metrics.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ . }}
      {{- end }}
      path: /api/prometheus
      {{- with .Values.metrics.serviceMonitor.bearerTokenFile }}
      bearerTokenFile: {{ . }}
      {{- end }}
      {{- with .Values.metrics.serviceMonitor.bearerTokenSecret }}
      bearerTokenSecret:
        name: {{ .name }}
        key: {{ .key }}
        {{- with .optional }}
        optional: {{ . }}
        {{- end }}
      {{- end }}
{{- end }}
