apiVersion: v2
name: home-assistant
description: Open source home automation that puts local control and privacy first
type: application
version: 1.30.3
# renovate: image=ghcr.io/home-assistant/home-assistant
appVersion: "2023.12.0"
keywords:
  - home-assistant
  - hass
  - homeassistant
  - smarthome
home: https://github.com/pree/helm-charts/tree/master/charts/home-assistant
icon: https://raw.githubusercontent.com/home-assistant/home-assistant.io/current/source/images/favicon-192x192.png
sources:
  - https://github.com/home-assistant/core
maintainers:
  - name: pree
    email: pascal@reeb.io
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts/
    version: 1.5.1
  - name: postgresql
    version: 13.2.24
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: mariadb
    version: 14.1.4
    repository: https://charts.bitnami.com/bitnami
    condition: mariadb.enabled
  - name: influxdb
    version: 5.11.1
    repository: https://charts.bitnami.com/bitnami
    condition: influxdb.enabled
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: use template to generate README.md
