apiVersion: v2
name: home-assistant
description: Open source home automation that puts local control and privacy first
type: application
version: 1.21.3
# renovate: image=ghcr.io/home-assistant/home-assistant
appVersion: "2023.7.1"
keywords:
  - home-assistant
  - hass
  - homeassistant
  - smarthome
home: https://github.com/pree/helm-charts/tree/master/charts/home-assistant
icon: https://raw.githubusercontent.com/home-assistant/core/dev/docs/source/_static/logo.png
sources:
  - https://github.com/home-assistant/core
maintainers:
  - name: pree
    email: pascal@reeb.io
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts/
    version: 1.5.1
  - name: postgresql
    version: 12.6.8
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: mariadb
    version: 12.2.8
    repository: https://charts.bitnami.com/bitnami
    condition: mariadb.enabled
  - name: influxdb
    version: 5.7.2
    repository: https://charts.bitnami.com/bitnami
    condition: influxdb.enabled
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: remove postgresql version pinning
