{{/* Make sure all variables are set properly */}}
{{- include "bjw-s.common.loader.init" . }}

{{/* Append the hardcoded settings */}}
{{- define "overseerr.harcodedValues" -}}
{{- end -}}
{{- $_ := mergeOverwrite .Values (include "overseerr.harcodedValues" . | fromYaml) -}}

{{/* Render the templates */}}
{{ include "bjw-s.common.loader.generate" . }}
