---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: {{ .Values.size }}
  nfs:
    path: {{ .Values.path }}
    server: {{ .Values.server }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}
spec:
  volumeName: {{ .Release.Name }}
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.size }}
