---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}
spec:
  accessModes:
    - ReadOnlyMany
  capacity:
    storage: "16Ti"
  nfs:
    path: {{ .Values.nfsMount.path }}
    server: {{ .Values.nfsMount.server }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.nfsMount.destination.namespace }}
spec:
  volumeName: {{ .Release.Name }}
  storageClassName: ""
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: {{ .Values.nfsMount.size }}
